Andreasens_Common_Name = [ 
'araucaria heterophylla',
'banksia robur',
'brittle gum',
'crassula ovata',
'rosemary',
'acacia floribunda',
'acacia trinervis',
'african iris',
'african tulip tree',
'all summer beauty',
'alligatorwood',
'alpengluhen',
'altona',
'american storax',
'american sweetgum',
'american tulip tree',
'ami pasquier',
'angled lobelia',
'angular sea-fig',
'anthos',
'areca palm',
'aroma doble',
'asiatic jasmine',
'australian banyan',
'australian lancewood',
'australian tea tree',
'australian teak',
'autumn zephyrlily',
'ayesha',
'bailmer',
'bamboo palm',
'banana shrub',
'bangalay',
'bangalow palm',
'bar-room plant',
'basket grass',
'bastard box',
'bastard jarrah',
'beach spider lily',
'beach tamarind',
'bears breeches',
'bearsfoot',
'beaute vendomoise',
'bhutan cypress',
'big blue lilyturf',
'bigleaf hydrangea',
'bilsted',
'bird of paradise',
'bird of paradise',
'birds nest fern',
'birrna',
'black birch',
'black gum',
'black gum',
'black olives',
'black olives',
'black poui',
'black sheoak',
'black she-oak',
'black tupelo ',
'black wattle',
'black-anther flax-lily',
'blackbutt',
'blaumeise',
'blue bonnet',
'blue bugle',
'blue chalksticks',
'blue fescue',
'blue flax-lily',
'blue gum',
'blue jacaranda',
'blue rock bindweed',
'blue spotted gum',
'blue spotted gum',
'blue wave',
'blueberry ash',
'blueberry ash',
'blueberry flax-lily',
'blueberry lily',
'blueberry lily',
'blue-leaved ironbark',
'blue-stem yucca',
'blushing bride',
'bony-tip fleabane',
'border grass',
'boston ivy',
'bower of beauty',
'bower plant',
'bower vine',
'box scrub',
'boxwood',
'brisbane box',
'brisbane golden wattle',
'broad leaved palm lily',
'broadleaf lady palm',
'broad-leaved banksia',
'broad-leaved paperbark',
'broad-leaved red ironbark',
'broad-leaved red ironbark',
'brush box',
'brush cherry',
'budjur',
'bugle',
'bugleherb',
'bugleweed',
'bull bay',
'burrawang',
'bush lily',
'butterfly palm',
'c.a citriodora',
'c.a eximia',
'c.a gummifera',
'c.a maculata',
'cabbage gum',
'cabbage-tree palm',
'canarian ivy',
'candleberry tree',
'cape jasmine',
'cape jessamine',
'cardboard cycad',
'cardboard palm',
'cardboard plant',
'cardboard sago',
'carpet bugleweed',
'carpetweed',
'carrol',
'carrol ironwood',
'carrotwood',
'cast-iron-plant',
'cherry alder',
'cherry alder',
'cherry satinash',
'cherry satinash',
'chicken tree',
'china tree',
'chinese banyan',
'chinese box',
'chinese elm',
'chinese fountaingrass',
'chinese ivy',
'chinese jasmine',
'chinese pennisetum',
'chinese pistache',
'chinese star jasmine',
'chinese tallow',
'chinese tallowtree',
'chinese wisteria',
'cinnamon myrtle',
'climbing fig',
'climbing guinea flower',
'clove lilli pilli',
'clove lilli pilli',
'coast banksia',
'coast banksia',
'coast wattle',
'coastal banksia',
'coastal rosemary',
'coastal tea tree',
'coastal westringia',
'cocktail',
'cogongrass',
'colonial pine',
'common box',
'common bugle',
'common camellia',
'common correa',
'common everlasting',
'common frangipani,',
'common frangipani,',
'common hop bush',
'common red',
'common tussock-grass',
'common tussock-grass',
'common violet',
'confederate jasmine',
'confederate jasmine',
'confederate jessamine',
'copalm balsam',
'coral fountain',
'coral plant',
'coralblow',
'corymbia citriodora',
'corymbia eximia',
'corymbia gummifera',
'corymbia gummifera',
'corymbia maculata',
'crane flower',
'crane flower',
'crape myrtle',
'creek bottlebrush',
'creek lilly-pilly',
'creek mat-rush',
'creek satinash',
'creeping boobialla',
'creeping cedar',
'creeping fig',
'creeping juniper',
'creeping myoporum',
'crepe myrtle',
'crepeflower',
'crimson',
'crows ash',
'crows nest fern',
'curtain fig',
'heath-leaved banksia.',
'banksia latifolia',
'cut-leaved daisy',
'danh-danh',
'dorrigo pine',
'double-flowering plum',
'double-flowering plum',
'dusky coral pea',
'dwarf cardamom',
'dwarf fountain grass',
'dwarf lilyturf',
'dwarf native myrtle',
'early green wattle',
'east asian white birch',
'eastern tiger swallowtail',
'elizabeth isaacs',
'english violet',
'eucalyptus citriodora',
'eucalyptus citriodora',
'europa',
'european box',
'european nettle tree',
'european white birch',
'european white birch',
'evergreen ash',
'exam tree',
'false sarsaparilla',
'fiddletree',
'firecracker plant',
'firescreen',
'flamevine',
'flax',
'flax-leaved paperbark',
'flooded gum',
'florida aspen',
'florists violet',
'forest oak',
'forest red gum',
'forever pink',
'fortnight lily',
'fountain plant',
'fountainbush',
'fountainplant',
'foxtail',
'foxtail fountain grass',
'frangipani',
'frangipani',
'french hydrangea',
'fringed wattle',
'bigleaf hydrangea',
'french hydrangea',
'lacecap hydrangea',
'mophead hydrangea',
'penny mac',
'gajumaru',
'gakuajisai',
'garden violet',
'gardenia',
'giant white bird of paradise',
'giant yucca',
'gingko',
'ginkgo',
'gold guinea plant',
'golden cane palm',
'golden guinea vine',
'golden wattle',
'goldenrain tree',
'gossamer wattle',
'grape ivy',
'gray popcorn tree',
'green ash',
'green mat-rush',
'green olives',
'green olives',
'green-leaved tamarind',
'grey box',
'grey gum',
'grey gum',
'grey myrtle',
'grey oak',
'ground blue-convolvulus',
'gu',
'gum-topped box',
'gymea lily',
'hairpin banksia',
'hairpin banksia',
'happy wanderer',
'harakeke',
'harbin pear',
'hawkesbury daisy',
'hazel pine',
'heath banksia',
'heavenly bamboo',
'hedgemaster',
'hill banksia',
'hills weeping fig',
'himalayan ash',
'himalayan cypress',
'honeyberry',
'honeysuckle',
'honeysuckle oak',
'hong kong hawthorn',
'hong kong hawthorn',
'hoop pine',
'hortensia',
'hybrid plane',
'hybrid plane',
'hybrid plane',
'illawara palm',
'illawarra flame tree',
'in',
'india hawthorn',
'india hawthorn',
'indian hawthorn',
'indian hawthorn',
'indian laurel',
'indica',
'iron tree',
'ironbark',
'ironwood',
'itabo',
'ivory curl',
'izote',
'jacaranda',
'jade plant',
'jamaican sago',
'japanese camellia',
'japanese crab',
'japanese creeper',
'japanese flowering crabapple',
'japanese ivy',
'japanese maple',
'japanese sago palm',
'jasmim laranja',
'jasmin',
'jasmine orange',
'kaffir lily',
'kangaroo grass',
'kanooka',
'karwinskya€™s fleabane',
'kentia palm',
'kidney weed',
'king alexander palm',
'king palm',
'king palm',
'king sago',
'knobby club-rush',
'knotted club-rush',
'kooigoed',
'kunai grass',
'lacebark elm',
'lacecap',
'lacecap hydrangea',
'lacewood',
'lacy tree fern',
'lady in red',
'lakeview jasmine',
'lambs-ear',
'lanarth white',
'lantern banksia',
'large leaf hop bush',
'latin american fleabane',
'laurestine',
'laurustinus',
'laurustinus viburnum',
'leaves and fruit',
'lemon bottlebrush',
'lemon myrtle',
'lemon scented ironwood',
'lemon scented myrtle',
'lemon-scented gum',
'lemon-scented gum',
'lemon-scented teatree',
'lenten rose',
'leptospermum laevigatum',
'leptospermum laevigatum',
'leptotes plinius',
'leptotes plinius',
'licorice-plant',
'lilac vine',
'lilacina',
'lilytree',
'lilyturf',
'lions tail',
'liquid amber',
'liquorice plant',
'living christmas tree',
'london plane',
'london plane',
'london plane',
'london planetree',
'london planetree',
'london planetree',
'long-leaf wax flower',
'long-leaved wattle',
'lote tree',
'lucky plant',
'm.a citrina',
'm.a salicina',
'm.a viminalis',
'ma',
'madder-leaved bauera',
'maidenhair tree',
'maikaika',
'malayan banyan',
'manchurian  pear',
'mangrove lily',
'mariesii grandiflora',
'mariesii perfecta',
'masja',
'mediterranean hackberry',
'melaleuca citrina',
'melaleuca salicina',
'melaleuca viminalis',
'mercury bay weed',
'metrosideros gummifera',
'mexican cycad',
'mexican fleabane',
'minerals',
'minerals',
'mock lime',
'mock orange',
'mondograss',
'money plant',
'money tree',
'monkey grass',
'monkeygrass',
'monstruosa',
'mophead',
'mophead hydrangea',
'moreton bay fig',
'moreton bay pine',
'mother-in-laws tongue',
'mountain gum',
'mugga ironbark',
'mugga, red ironbark',
'muggago',
'murta de cheiro',
'nandina',
'narrow-leaved',
'narrow-leaved bird of paradise',
'narrow-leaved ironbark',
'narrow-leaved palm lily',
'narrow-leaved paperbark',
'narrow-leaved red ironbark',
'natal lily',
'native frangipani',
'native fuchsia',
'native ginger',
'native lilac',
'neverbreak',
'new england banksia',
'new zealand christmas bush',
'new zealand christmas tree',
'new zealand flax',
'new zealand hemp',
'new zealand pohutukawa',
'new zealand rock lily',
'niaouli',
'nigra',
'nikko blue',
'norfolk island pine',
'norfolk pine',
'northern bangalow palm',
'obtuse-leaved grevillea',
'oil-cured olives',
'oil-cured olives',
'old man banksia',
'old world species',
'old world species',
'old world species',
'old world species',
'old world sycamore',
'olive',
'orange jessamine',
'orange trumpetvine',
'oriental plane',
'oyster plant',
'p.a myoporoides',
'pa',
'pohutukawa',
'palmate maple',
'paper bark tea tree',
'paroo lily',
'penny mac',
'penny mac',
'peruvian swamp lily',
'philotheca myoporoides',
'philotheca myoporoides',
'pia',
'picholine or directly-brined type',
'picholine or directly-brined type',
'pigface',
'pin oak',
'pink box',
'pink spider flower',
'plumbago blue',
'plumeria',
'plumeria',
'polynesian pine',
'port jackson fig',
'port wine magnolia',
'poverty bush',
'prairie crabapple',
'prickly paperbark',
'prickly rasp fern',
'prickly-leaved banksia',
'prickly-leaved paperbark',
'prickly-leaved paperbark',
'pride of india',
'punk tree',
'purple chokeberry',
'purple coral pea',
'purple panic',
'purple-leafed plum',
'purple-leafed plum',
'queensland blue gum',
'queensland box',
'queensland kauri pine',
'queensland pine',
'red ash',
'red back ginger',
'red bloodwood',
'red emperor maple',
'red frangipani',
'red frangipani',
'red grass',
'red gum',
'red head',
'red honeysuckle',
'red ironbark',
'red ironbark',
'red irongum',
'red oat grass',
'red paucipan',
'red paucipan',
'red spotted gum',
'red-fruit saw-sedge',
'redgum',
'red-jasmine',
'red-jasmine',
'renga lily',
'rengarenga',
'riberry',
'riberry',
'riberry',
'riberry',
'richmond river pine',
'ripe olives',
'ripe olives',
'river birch',
'river black-oak',
'river lily',
'river oak',
'river oak',
'river she-oak',
'rock thryptomene',
'rocky daisy',
'rooigras',
'rose apple',
'rose gum',
'rose of winter',
'rose she-oak',
'rosemary',
'rosemary grevillea',
'rough-barked apple',
'rush-leaved strelitzia',
'rusty fig',
's.a cooperi',
's.a rosmarinus',
's.a smithii',
's.a virgata',
'sacred bamboo',
'sago cycad',
'sago palm',
'sallow wattle',
'sally',
'salvia rosmarinus',
'sannantha virgata',
'sannantha virgata',
'santa barbara daisy',
'sasanqua camellia',
'satin-walnut',
'satinwood',
'satsuki azalea',
'saucer magnolia',
'saw banksia',
'saw-tooth banksia',
'scaly tree fern',
'schnapper point',
'scribbly gum',
'scrub cherry',
'sea dock',
'shellflower',
'shore juniper',
'showy crabapple',
'shrubby bindweed',
'shrubby germander',
'sickle wattle',
'silver birch',
'silverbush',
'silver-bush everlasting flower',
'slaty gum',
'slender palm lily',
'small leaved lilly pilly',
'small leaved lilly pilly',
'small leaved myoporum',
'small-leaved apple',
'smooth japanese-maple',
'smooth-barked apple',
'smooth-barked kauri',
'snake plant',
'snake vine',
'snow-in-summer',
'snow-in-summer',
'society garlic',
'soeur therese',
'soft-tip yucca',
'song of india',
'song of jamaica',
'sotetsu',
'sour gum',
'sour gum',
'southern jasmine',
'southern magnolia',
'southern magnolia',
'southern mahogany',
'spanish daisy',
'spanish or sevillian type',
'spanish or sevillian type',
'sphaeropteris cooperi',
'sphaeropteris_cooperi',
'spiky-headed mat-rush',
'spineless yucca',
'spiny-head mat-rush',
'spotted gum',
'spotted gum',
'spreading flax-lily',
'star jasmine',
'star jasmine',
'star magnolia,',
'star pine',
'star-leaved gum',
'strelitzia',
'supplementum plantarum',
'supplementum plantarum',
'swamp banksia',
'swamp foxtail grass',
'swamp lily',
'swamp mahogany',
'swamp messmate',
'swamp oak',
'swamp she-oak',
'swamp spanish oak',
'swans neck',
'sweet viburnum',
'sweet violet',
'sweetgum',
'sydney blue gum',
'sydney golden wattle',
'sydney red gum',
'syzygium smithii',
't.a plinius',
't.a sebifera',
'table olives',
'table olives',
'tall sedge',
'tallowood',
'tallowwood',
'tantoon',
'tasman flax-lily',
'tasmanian flax-lily',
'taube',
'temple tree',
'temple tree',
'texas crabapple',
'thatch palm',
'the fern tree',
'the jacaranda city',
'thyme honey-myrtle',
'tick bush',
'tokyo delight',
'traders compass',
'trailing dusty miller',
'tree germander',
'triadica sebifera',
'triangle tree',
'tricolor',
'trident maple',
'tsubaki',
'tuckeroo',
'tulip lancewood',
'tulip poplar',
'tulip tree',
'tuliptree',
'tulipwood',
'tulipwood',
'tupelo',
'tupelo ',
'turpentine tree',
'twist-n-shout',
'ussurian pear',
'varnish tree',
'veitchii',
'veronica diosmifolia',
'vine lilac',
'vinegartree',
'vipers bowstring hemp',
'waraburra',
'warty birch',
'water birch',
'water gum',
'water-cured type',
'water-cured type',
'watergum',
'weeping acacia',
'weeping bottlebrush',
'weeping lilli pilli',
'westfalen',
'white banksia',
'white bottlebrush',
'white bottlebrush',
'white champaca',
'white correa',
'white feather honeymyrtle',
'white honeysuckle',
'white jade orchid tree',
'white kunzea',
'white sallow wattle',
'white sandalwood',
'white windflower',
'whitewood',
'wild banana',
'willow bottlebrush',
'willow-leaved hakea',
'wonga wonga vine',
'wood violet',
'woodbine',
'woolly hedgenettle',
'woollybutt',
'yanderra',
'yellow bloodwood',
'yellow bloodwood',
'yellow box',
'yellow buttons',
'yellow palm',
'yellow-poplar',
'yucca cane',
'yulan magnolia',
'zebra blue',
]
